# Generated by Django 4.2.1 on 2023-05-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
