# Generated by Django 4.2.1 on 2023-06-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ContactUs', 'verbose_name_plural': 'ContactUs'},
        ),
    ]
