# Generated by Django 4.2.1 on 2023-06-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(null=True, upload_to='media/order'),
        ),
    ]
