# Generated by Django 4.2.1 on 2023-05-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug_alter_producttag_slug'),
        ('order', '0002_orderdetails_price_orderdetails_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'OrderDetails', 'verbose_name_plural': 'OrderDetails'},
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariation'),
        ),
    ]
