# Generated by Django 4.2.1 on 2023-06-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderdetails_options_orderdetails_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='Total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
