# Generated by Django 4.2.1 on 2023-06-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderdetails_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
