# Generated by Django 4.2.1 on 2023-06-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_product_category'),
        ('order', '0005_orderdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderimage', to='product.product'),
        ),
    ]
